const WORKER_URL = "https://steam-game-night-api.chrisalfonso1238.workers.dev";
let players = [], matchingGames = [], excludedGames = new Set(), rotation = 0, spinning = false;
const $ = id => document.getElementById(id);
const playersEl=$('players'), addBtn=$('add'), checkBtn=$('check'), ownership=$('ownership'), gamesEl=$('games'), countEl=$('count'), statusEl=$('status'), searchEl=$('gameSearch'), canvas=$('wheel'), spinBtn=$('spin'), wheelCenter=$('wheelCenter'), winnerEl=$('winner'), wheelCountEl=$('wheelCount'), excludedCountEl=$('excludedCount'), excludedListEl=$('excludedList'), restoreAllBtn=$('restoreAll');
const ctx=canvas.getContext('2d');

function setStatus(message,error=false){statusEl.classList.toggle('error',error);statusEl.innerHTML=`<span class="status-dot">${error?'!':'✓'}</span><span>${escapeHTML(message)}</span>`}
function createPlayerInput(value=''){
  const row=document.createElement('div'); row.className='player-input';
  const input=document.createElement('input'); input.className='steam-profile-input'; input.type='url'; input.placeholder='https://steamcommunity.com/profiles/7656119.../'; input.value=value;
  const remove=document.createElement('button'); remove.className='remove-player'; remove.type='button'; remove.textContent='×';
  remove.onclick=()=>{if(document.querySelectorAll('.steam-profile-input').length<=2){setStatus('You need at least two Steam profiles.',true);return}row.remove()};
  row.append(input,remove); playersEl.append(row);
}
function profileURLs(){return [...document.querySelectorAll('.steam-profile-input')].map(x=>x.value.trim()).filter(Boolean)}
async function fetchLibrary(profile){const r=await fetch(`${WORKER_URL}/library?profile=${encodeURIComponent(profile)}`);let d;try{d=await r.json()}catch{throw new Error('The server returned an invalid response.')}if(!r.ok||!d.success)throw new Error(d.error||'Could not load this Steam library.');return{profile,steamid:d.steamid,gameCount:d.game_count,games:d.games}}
async function checkGames(){const urls=profileURLs();if(urls.length<2){setStatus('Enter at least two Steam profiles.',true);return}checkBtn.disabled=true;setStatus(`Loading ${urls.length} Steam libraries...`);try{players=await Promise.all(urls.map(fetchLibrary));excludedGames.clear();compareLibraries();setStatus(`${matchingGames.length} matching games found. ${wheelGames().length} are on the wheel.`)}catch(e){setStatus(e.message,true)}finally{checkBtn.disabled=false}}
function compareLibraries(){const map=new Map();players.forEach(p=>p.games.forEach(g=>{if(!map.has(g.appid))map.set(g.appid,{...g,owners:0});map.get(g.appid).owners++}));let min=ownership.value==='all'?players.length:Number(ownership.value)||players.length;matchingGames=[...map.values()].filter(g=>g.owners>=min).sort((a,b)=>a.name.localeCompare(b.name));countEl.textContent=matchingGames.length;renderGames();renderExcluded();drawWheel()}
function renderGames(){const q=(searchEl.value||'').trim().toLowerCase();const shown=matchingGames.filter(g=>g.name.toLowerCase().includes(q));gamesEl.innerHTML='';if(!shown.length){gamesEl.innerHTML='<div class="no-games">No matching games found.</div>';return}shown.forEach(g=>{const excluded=excludedGames.has(g.appid);const card=document.createElement('article');card.className=`game-card${excluded?' excluded':''}`;const image=`https://cdn.cloudflare.steamstatic.com/steam/apps/${g.appid}/header.jpg`;card.innerHTML=`<div class="game-image-wrap"><img src="${image}" alt="${escapeHTML(g.name)}" loading="lazy"><span class="excluded-badge">Excluded</span></div><div class="game-info"><h3 title="${escapeHTML(g.name)}">${escapeHTML(g.name)}</h3><p>👥 Owned by ${g.owners} of ${players.length} players</p><div class="game-actions"><a href="https://store.steampowered.com/app/${g.appid}/" target="_blank" rel="noopener">Steam ↗</a><button class="exclude-btn ${excluded?'restore':''}" type="button">${excluded?'↩ Restore':'− Exclude'}</button></div></div>`;card.querySelector('.exclude-btn').onclick=()=>toggleExcluded(g.appid);gamesEl.append(card)})}
function toggleExcluded(appid){if(excludedGames.has(appid))excludedGames.delete(appid);else excludedGames.add(appid);renderGames();renderExcluded();drawWheel();winnerEl.textContent='Spin the wheel to pick a game!';setStatus(`${wheelGames().length} of ${matchingGames.length} matching games are on the wheel.`)}
function renderExcluded(){const excluded=matchingGames.filter(g=>excludedGames.has(g.appid));excludedCountEl.textContent=excluded.length;excludedListEl.innerHTML='';if(!excluded.length){excludedListEl.innerHTML='<span class="excluded-empty">No games excluded.</span>';restoreAllBtn.disabled=true}else{restoreAllBtn.disabled=false;excluded.forEach(g=>{const chip=document.createElement('button');chip.className='excluded-chip';chip.type='button';chip.title='Click to restore';chip.innerHTML=`${escapeHTML(g.name)} <b>×</b>`;chip.onclick=()=>toggleExcluded(g.appid);excludedListEl.append(chip)})}}
function restoreAll(){excludedGames.clear();renderGames();renderExcluded();drawWheel();setStatus(`All ${matchingGames.length} matching games are back on the wheel.`)}
function escapeHTML(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function wheelGames(){return matchingGames.filter(g=>!excludedGames.has(g.appid))}
function drawWheel(){const list=wheelGames(),w=canvas.width,c=w/2,r=w*.46;wheelCountEl.textContent=list.length;ctx.clearRect(0,0,w,w);ctx.save();ctx.translate(c,c);ctx.rotate(rotation);if(!list.length){ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fillStyle='#122544';ctx.fill();ctx.strokeStyle='#5868ff';ctx.lineWidth=10;ctx.stroke();ctx.fillStyle='#9fb0cc';ctx.font='700 28px system-ui';ctx.textAlign='center';ctx.fillText(matchingGames.length?'ALL EXCLUDED':'CHECK GAMES',0,10);ctx.restore();return}const arc=Math.PI*2/list.length;const palettes=[['#218dff','#3157e8'],['#7557ff','#b33fe1'],['#dc35c8','#7a4dff']];list.forEach((g,i)=>{const a=i*arc;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,a,a+arc);ctx.closePath();const grad=ctx.createLinearGradient(-r,-r,r,r),p=palettes[i%palettes.length];grad.addColorStop(0,p[0]);grad.addColorStop(1,p[1]);ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle='rgba(255,255,255,.13)';ctx.lineWidth=list.length>45?.7:1.5;ctx.stroke();if(list.length<=28){ctx.save();ctx.rotate(a+arc/2);ctx.translate(r*.68,0);ctx.rotate(Math.PI/2);ctx.fillStyle='white';ctx.font=`700 ${list.length>18?11:list.length>12?13:16}px system-ui`;ctx.textAlign='center';const max=list.length>18?12:16;const name=g.name.length>max?g.name.slice(0,max-1)+'…':g.name;ctx.fillText(name,0,4);ctx.restore()}});ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.strokeStyle='#8f68ff';ctx.lineWidth=12;ctx.stroke();ctx.restore()}
function spin(){const list=wheelGames();if(spinning||!list.length){if(!list.length)setStatus(matchingGames.length?'Restore at least one excluded game before spinning.':'Check your Steam libraries first.',true);return}spinning=true;spinBtn.disabled=true;const winnerIndex=Math.floor(Math.random()*list.length),arc=Math.PI*2/list.length;const current=((rotation%(Math.PI*2))+Math.PI*2)%(Math.PI*2);const target=-Math.PI/2-(winnerIndex+.5)*arc;let delta=target-current;while(delta<0)delta+=Math.PI*2;const extra=Math.PI*2*(5+Math.floor(Math.random()*3));const start=rotation,end=rotation+delta+extra,duration=4300,startTime=performance.now();winnerEl.textContent='Spinning…';function frame(now){const t=Math.min((now-startTime)/duration,1),ease=1-Math.pow(1-t,4);rotation=start+(end-start)*ease;drawWheel();if(t<1)requestAnimationFrame(frame);else{rotation=end%(Math.PI*2);drawWheel();winnerEl.textContent=list[winnerIndex].name;setStatus(`Tonight's pick: ${list[winnerIndex].name}`);spinning=false;spinBtn.disabled=false}}requestAnimationFrame(frame)}
addBtn.addEventListener('click',()=>createPlayerInput());checkBtn.addEventListener('click',checkGames);ownership.addEventListener('change',()=>players.length&&compareLibraries());searchEl.addEventListener('input',renderGames);spinBtn.addEventListener('click',spin);wheelCenter.addEventListener('click',spin);restoreAllBtn.addEventListener('click',restoreAll);window.addEventListener('resize',drawWheel);
createPlayerInput();createPlayerInput();renderExcluded();drawWheel();
