const playersEl=document.querySelector('#players'),gamesEl=document.querySelector('#games'),countEl=document.querySelector('#count'),statusEl=document.querySelector('#status'),winnerEl=document.querySelector('#winner');
const canvas=document.querySelector('#wheel'),ctx=canvas.getContext('2d');let matches=[],rotation=0,spinning=false;
const DEMO={
  1:[['Terraria',true],['Lethal Company',true],['Stardew Valley',true],['Portal 2',true],['Hades',false],['Left 4 Dead 2',true]],
  2:[['Terraria',true],['Lethal Company',true],['Stardew Valley',true],['Portal 2',true],['Risk of Rain 2',true]],
  3:[['Terraria',true],['Lethal Company',true],['Portal 2',true],['Left 4 Dead 2',true]],
  4:[['Terraria',true],['Lethal Company',true],['Stardew Valley',true],['Portal 2',true]]
};
function addPlayer(value=''){const d=document.createElement('div');d.className='player';d.innerHTML=`<input placeholder="https://steamcommunity.com/id/username" value="${value}"><button class="remove">Remove</button>`;d.querySelector('.remove').onclick=()=>{d.remove();syncOwnership()};playersEl.appendChild(d);syncOwnership()}
function syncOwnership(){const n=playersEl.querySelectorAll('input').length,s=document.querySelector('#ownership');s.innerHTML='<option value="all">Everyone</option>';for(let i=2;i<n;i++)s.innerHTML+=`<option value="${i}">At least ${i} players</option>`}
async function fetchSteamLibrary(profileUrl){throw new Error('Live Steam endpoint not connected yet.');}
function demoLibrary(i){return (DEMO[(i%4)+1]||[]).map(([name,multi])=>({name,multiplayer:multi}));}
function compare(libs){const needed=document.querySelector('#ownership').value==='all'?libs.length:+document.querySelector('#ownership').value;const onlyMulti=document.querySelector('#coop').checked;const map=new Map();libs.forEach(lib=>lib.forEach(g=>{const x=map.get(g.name)||{name:g.name,count:0,multiplayer:g.multiplayer};x.count++;x.multiplayer ||= g.multiplayer;map.set(g.name,x)}));return [...map.values()].filter(g=>g.count>=needed&&(!onlyMulti||g.multiplayer)).sort((a,b)=>a.name.localeCompare(b.name));}
function render(){gamesEl.innerHTML=matches.map(g=>`<div class="game">🎮 ${g.name}</div>`).join('');countEl.textContent=matches.length;drawWheel()}
function drawWheel(){ctx.clearRect(0,0,520,520);const n=Math.max(matches.length,1),r=245,c=260;ctx.save();ctx.translate(c,c);ctx.rotate(rotation);for(let i=0;i<n;i++){const a0=i*2*Math.PI/n,a1=(i+1)*2*Math.PI/n;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,a0,a1);ctx.closePath();ctx.fillStyle=`hsl(${(i*360/n)%360} 58% ${i%2?42:34}%)`;ctx.fill();ctx.strokeStyle='#0b1520';ctx.stroke();if(matches.length){ctx.save();ctx.rotate((a0+a1)/2);ctx.textAlign='right';ctx.fillStyle='white';ctx.font=`700 ${Math.max(11,Math.min(18,170/n+9))}px system-ui`;let t=matches[i].name;t=t.length>23?t.slice(0,21)+'…':t;ctx.fillText(t,r-18,6);ctx.restore()}}ctx.restore();if(!matches.length){ctx.fillStyle='#8da6b8';ctx.font='20px system-ui';ctx.textAlign='center';ctx.fillText('Check games to build the wheel',260,265)}}
document.querySelector('#add').onclick=()=>addPlayer();document.querySelector('#ownership').onchange=()=>document.querySelector('#check').click();document.querySelector('#coop').onchange=()=>document.querySelector('#check').click();
document.querySelector('#check').onclick=async()=>{const urls=[...playersEl.querySelectorAll('input')].map(x=>x.value.trim()).filter(Boolean);if(urls.length<2){statusEl.textContent='Add at least two Steam profile links.';return}statusEl.textContent='Checking libraries…';const libs=urls.map((_,i)=>demoLibrary(i));matches=compare(libs);statusEl.textContent=`Demo check complete: ${urls.length} players compared.`;winnerEl.textContent='';render()};
document.querySelector('#spin').onclick=()=>{if(spinning||!matches.length)return;spinning=true;winnerEl.textContent='';const chosen=Math.floor(Math.random()*matches.length),slice=2*Math.PI/matches.length,target=(Math.PI*1.5)-(chosen+.5)*slice;const start=rotation,end=target+Math.PI*2*(6+Math.floor(Math.random()*3)),t0=performance.now(),dur=4200;function anim(t){const p=Math.min(1,(t-t0)/dur),e=1-Math.pow(1-p,4);rotation=start+(end-start)*e;drawWheel();if(p<1)requestAnimationFrame(anim);else{rotation%=Math.PI*2;spinning=false;winnerEl.textContent=`🎉 ${matches[chosen].name}`}}requestAnimationFrame(anim)};
addPlayer();addPlayer();drawWheel();
