const WORKER_URL = "https://steam-game-night-api.chrisalfonso1238.workers.dev";
let players = [], matchingGames = [], rotation = 0, spinning = false;
const $ = id => document.getElementById(id);
const playersEl=$('players'), addBtn=$('add'), checkBtn=$('check'), ownership=$('ownership'), gamesEl=$('games'), countEl=$('count'), statusEl=$('status'), searchEl=$('gameSearch'), canvas=$('wheel'), spinBtn=$('spin'), wheelCenter=$('wheelCenter'), winnerEl=$('winner');
const ctx=canvas.getContext('2d');

function setStatus(message,error=false){statusEl.classList.toggle('error',error);statusEl.innerHTML=`<span class="status-dot">${error?'!':'✓'}</span><span>${escapeHTML(message)}</span>`}
function createPlayerInput(value=''){
  const row=document.createElement('div'); row.className='player-input';
  const input=document.createElement('input'); input.className='steam-profile-input'; input.type='url'; input.placeholder='https://steamcommunity.com/profiles/7656119.../'; input.value=value;
  const remove=document.createElement('button'); remove.className='remove-player'; remove.type='button'; remove.textContent='×';
  remove.onclick=()=>{if(document.querySelectorAll('.steam-profile-input').length<=2){setStatus('You need at least two Steam profiles.',true);return}row.remove()};
  row.append(input,remove); playersEl.append(row);
}
function profileURLs(){return [...document.querySelectorAll('.steam-profile-input')].map(x=>x.value.trim()).filter(Boolean)}
async function fetchLibrary(profile){const r=await fetch(`${WORKER_URL}/library?profile=${encodeURIComponent(profile)}`);let d;try{d=await r.json()}catch{throw new Error('The server returned an invalid response.')}if(!r.ok||!d.success)throw new Error(d.error||'Could not load this Steam library.');return{profile,steamid:d.steamid,gameCount:d.game_count,games:d.games}}
async function checkGames(){const urls=profileURLs();if(urls.length<2){setStatus('Enter at least two Steam profiles.',true);return}checkBtn.disabled=true;setStatus(`Loading ${urls.length} Steam libraries...`);try{players=await Promise.all(urls.map(fetchLibrary));compareLibraries();setStatus(`${matchingGames.length} matching games found!`)}catch(e){setStatus(e.message,true)}finally{checkBtn.disabled=false}}
function compareLibraries(){const map=new Map();players.forEach(p=>p.games.forEach(g=>{if(!map.has(g.appid))map.set(g.appid,{...g,owners:0});map.get(g.appid).owners++}));let min=ownership.value==='all'?players.length:Number(ownership.value)||players.length;matchingGames=[...map.values()].filter(g=>g.owners>=min).sort((a,b)=>a.name.localeCompare(b.name));countEl.textContent=matchingGames.length;renderGames();drawWheel()}
function renderGames(){const q=(searchEl.value||'').trim().toLowerCase();const shown=matchingGames.filter(g=>g.name.toLowerCase().includes(q));gamesEl.innerHTML='';if(!shown.length){gamesEl.innerHTML='<div class="no-games">No matching games found.</div>';return}shown.forEach(g=>{const card=document.createElement('article');card.className='game-card';const image=`https://cdn.cloudflare.steamstatic.com/steam/apps/${g.appid}/header.jpg`;card.innerHTML=`<img src="${image}" alt="${escapeHTML(g.name)}" loading="lazy"><div class="game-info"><h3 title="${escapeHTML(g.name)}">${escapeHTML(g.name)}</h3><p>👥 Owned by ${g.owners} of ${players.length} players</p><a href="https://store.steampowered.com/app/${g.appid}/" target="_blank" rel="noopener">View on Steam ↗</a></div>`;gamesEl.append(card)})}
function escapeHTML(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function wheelGames(){if(matchingGames.length<=12)return matchingGames;return matchingGames.slice(0,12)}
function drawWheel(){const list=wheelGames(),w=canvas.width,c=w/2,r=w*.46;ctx.clearRect(0,0,w,w);ctx.save();ctx.translate(c,c);ctx.rotate(rotation);if(!list.length){ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fillStyle='#122544';ctx.fill();ctx.strokeStyle='#5868ff';ctx.lineWidth=10;ctx.stroke();ctx.fillStyle='#9fb0cc';ctx.font='700 28px system-ui';ctx.textAlign='center';ctx.fillText('CHECK GAMES',0,10);ctx.restore();return}const arc=Math.PI*2/list.length;list.forEach((g,i)=>{const a=i*arc;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,a,a+arc);ctx.closePath();const grad=ctx.createLinearGradient(-r,-r,r,r);const palettes=[['#218dff','#3157e8'],['#7557ff','#b33fe1'],['#dc35c8','#7a4dff']];const p=palettes[i%palettes.length];grad.addColorStop(0,p[0]);grad.addColorStop(1,p[1]);ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle='rgba(255,255,255,.14)';ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.rotate(a+arc/2);ctx.translate(r*.67,0);ctx.rotate(Math.PI/2);ctx.fillStyle='white';ctx.font=`700 ${list.length>8?16:19}px system-ui`;ctx.textAlign='center';let name=g.name.length>16?g.name.slice(0,14)+'…':g.name;ctx.fillText(name,0,5);ctx.restore()});ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.strokeStyle='#8f68ff';ctx.lineWidth=12;ctx.stroke();ctx.restore()}
function spin(){if(spinning||!matchingGames.length){if(!matchingGames.length)setStatus('Check your Steam libraries first.',true);return}spinning=true;spinBtn.disabled=true;const list=wheelGames();const winnerIndex=Math.floor(Math.random()*list.length),arc=Math.PI*2/list.length;const current=rotation%(Math.PI*2);const target=-Math.PI/2-(winnerIndex+.5)*arc;const extra=Math.PI*2*(5+Math.floor(Math.random()*3));const start=rotation,end=rotation+(target-current)+extra,duration=4300,startTime=performance.now();winnerEl.textContent='Spinning…';function frame(now){const t=Math.min((now-startTime)/duration,1),ease=1-Math.pow(1-t,4);rotation=start+(end-start)*ease;drawWheel();if(t<1)requestAnimationFrame(frame);else{rotation=end%(Math.PI*2);drawWheel();winnerEl.textContent=list[winnerIndex].name;setStatus(`Tonight's pick: ${list[winnerIndex].name}`);spinning=false;spinBtn.disabled=false}}requestAnimationFrame(frame)}
addBtn.addEventListener('click',()=>createPlayerInput());checkBtn.addEventListener('click',checkGames);ownership.addEventListener('change',()=>players.length&&compareLibraries());searchEl.addEventListener('input',renderGames);spinBtn.addEventListener('click',spin);wheelCenter.addEventListener('click',spin);window.addEventListener('resize',drawWheel);
createPlayerInput();createPlayerInput();drawWheel();
